### ISSUE TITLE
import and template

### ISSUE THREAD

**Issue by joelcnz** [qznc/d-money#1]
I get this:

Joels-MacBook-Pro:Money joelcnz$ dub
Performing "debug" build using dmd for x86_64.
money 1.0.0: target for configuration "library" is up to date.
jmoney ~master: building configuration "application"...
source/app.d(6,14): Error: template instance money!"EUR" money is not a template declaration, it is a import
dmd failed with exit code 1.
Joels-MacBook-Pro:Money joelcnz$ 

I think the module needs a new name.

**Comment by qznc** [comment]
How does your `source/app.d` look like? I cannot reproduce it like this.

**Comment by qznc** [comment]
Ok, I can. Epic fail. :-1:  I wonder why I did not see this earlier?

**Comment by qznc** [comment]
Fixed.
