### ISSUE TITLE
we need add opCast, e.g. back to double

### ISSUE THREAD

**Issue by mw66** [qznc/d-money#10]
e.g. after calculating the money value using this library, the value needs to feed into another library for some math operation (or for drawing a chart, i.e money => pixel height), which takes D native type double.

**Comment by mw66** [comment]
this issue is related to https://github.com/qznc/d-money/issues/9

If we can convert back to double, I can calculate how many times BG is richer than me.

In the current library, I don't have a way to calculate it.

**Comment by mw66** [comment]
```
    T opBinary(string op)(const long rhs) const
```
and can we have LHS?
```
    T opBinary(string op)(const long lhs) const
```

e.g. 
$5 x 4 = $20
4 x $5 = $20 too!

**Comment by denizzzka** [comment]
It's too dangerous as for me

> If we can convert back to double, I can calculate how many times BG is richer than me.

Only with nearly precission

**Comment by mw66** [comment]
> It's too dangerous as for me
> 
> > If we can convert back to double, I can calculate how many times BG is richer than me.
> 
> Only with nearly precission

Well, we are talking about opCast, if the user *explicitly* cast, s/he knows what s/he is doing.

There are use cases where we need this, e.g. in my above calculating pixel height charting example, I don't care the precision.  But I need this functionality to be able to cast to double.

**Comment by mw66** [comment]
> ```
>     T opBinary(string op)(const long rhs) const
> ```
> 
> and can we have LHS?
> 
> ```
>     T opBinary(string op)(const long lhs) const
> ```
> 
> e.g.
> $5 x 4 = $20
> 4 x $5 = $20 too!

oh, it's opBinaryRight.
