### ISSUE TITLE
bug! EUR("1.23456")  ==> ctor ==> 3.3456EUR !

### ISSUE THREAD

**Issue by mw66** [qznc/d-money#11]
```
$ cat m.d
/+dub.sdl:
dependency "money" version="~>2.3.1"
+/

import std.stdio;
import money;

alias EUR = currency!("EUR");

void main() {
  EUR x = EUR( 1.23456 );
  EUR y = EUR("1.23456");
  writeln(x);
  writeln(y);
  assert(x == y);
}

$ dub m.d
1.2346EUR
3.3456EUR
core.exception.AssertError@m.d(15): Assertion failure
----------------
??:? _d_assertp [0x52b005]
m.d:15 _Dmain [0x4dec36]
Program exited with code 1

```

The reason is pow10(x) doesn't handle negative x at all.

https://github.com/qznc/d-money/blob/master/source/money.d#L64

when called from

https://github.com/qznc/d-money/blob/master/source/money.d#L107

with x = -1

BTW, why use a recursive function instead of a simple loop to calc pow10?

**Comment by mw66** [comment]
by loop, I mean:

```
long pow10(int x)
{
  assert(x >= 0);  // you only handle non-neg x
  int r = 1;
  for (int i = x; i--> 0; ) {
    r *= 10;
  }
  return r;
}
```

**Comment by mw66** [comment]
For the fix, it's better avoid writing own regex, just use standard library:

https://stackoverflow.com/questions/12605641/d-programming-parse-or-convert-string-to-double

```
  amount  = to!float(str) * pow10(dec_places);
```



```
import std.conv;
import std.stdio;    

void main() {
    float x = to!float("234.32");
    double y = to!double("234.32");

    writefln("And the float is: %f\nHey, we also got a double: %f", x, y);
}
```

**Comment by mw66** [comment]
And for practical purpose, the pow10, can be just a lookup table for small values:
e.g. upto the dec_places (default to 4), which can be statically generated:

lookup_table[] = [1, 10, 100, 1000, 10000]

**Comment by schveiguy** [comment]
Not able to commit to this repository, I'm not sure if @qznc is still active here. But I faced a similar problem with string parsing in a similar library, mostly because of the inaccuracies of floating point (the library used the technique suggested here -- convert to float, and then to integer).

We solved this in a new library by manipulating the string to be parseable directly to the storage integer form. See the [result](https://github.com/m3m0ry/fixedpoint/blob/78f8b4943645b35be09919695ab413cefaa5be63/fixedpoint/fixed.d#L54), maybe it can be used here as well.

**Comment by joelcnz** [comment]
@schveiguy I've been using this library. Could you fork it and fix it? I've got money entries dating back to the middle of 2009! If @qznc has abandoned this one.

**Comment by mw66** [comment]
@joelcnz 

for the time being, you can use this package

https://github.com/m3m0ry/fixedpoint/

e.g.
```
  import fixedpoint.fixed : Fixed;
  alias EUR = Fixed!4;
```

but this package won't check for overflows:

https://github.com/m3m0ry/fixedpoint/issues/4

**Comment by joelcnz** [comment]
Thanks @mingwugmail - I taken notes for later.

**Comment by mw66** [comment]
@joelcnz 

FYI

https://github.com/qznc/d-money/pull/12

**Comment by qznc** [comment]
Sorry for neglecting you. I want to maintain this further but I'm not checking Github that often anymore. Thanks everybody for discussion here!

I reviewed the pull request and only had one small request before merging it.

**Comment by joelcnz** [comment]
Thanks @qznc.
