### ISSUE TITLE
currency.this(string) isn't constructs negative values

### ISSUE THREAD

**Issue by denizzzka** [qznc/d-money#8]
```D
/+ dub.sdl:
name "hello_world"
dependency "money" version="*"
+/

import std.stdio;
import money;

alias T1 = currency!("T1", 2);
alias T2 = currency!("T2", 2, roundingMode.UNNECESSARY);

void main() {
    auto t1 = T1(-123.45);
    auto t2 = T1("-123.45");

    t1.writeln; // -123.-45T1 (extra minus in toString?)
    t2.writeln; // positive value, but should be negative

    assert(t1 == t2); // failure
}
```

```
$ dub run union_bug.d  --single
Performing "debug" build using /usr/bin/dmd for x86_64.
money 2.3.0: target for configuration "library" is up to date.
hello_world ~master: building configuration "application"...
Linking...
To force a rebuild of up-to-date targets, run again with --force.
Running ./hello_world 
-123.-45T1
123.45T1
core.exception.AssertError@union_bug.d(19): Assertion failure
----------------
??:? _d_assertp [0x77087198]
union_bug.d:19 _Dmain [0x7703cfaf]
Program exited with code 1
```

**Comment by denizzzka** [comment]
not a bug?

**Comment by qznc** [comment]
Sorry, I was confused about this "merged" icon. Thank you very much for reporting this. I just pushed a fix.

I have not fixed anything about T2. My guess is that `T2(-123.45)` triggering "Rounding is forbidden" is the problem?

That is a good question. Lots of numbers cannot be [represented exactly in floating point](https://stackoverflow.com/q/12124936/2361979), so it seems safer to me that the double-constructor always fails with rounding mode "unnecessary".

**Comment by denizzzka** [comment]
>  My guess is that T2(-123.45) triggering "Rounding is forbidden" is the problem?

Just weak selection for example code

**Comment by qznc** [comment]
Great. Then 2.3.1 contains the fix for this issue. I wish I were a faster maintainer.
